language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: l4k74yUEY4J0z01uM155Py2cOuvBNpFAaOf2Uq5p/D+bZz1BDumFGszNKxZi8m9UjuPxz8S4Z8wlVPRiBPvq/9Ee2OLFqiRlJ/PqVzj5KvJkclBgA7JErIsLpfRBnZBq5UmTQb14+Slyuyc0YJVY/M/F29fymBoWNOfEtuBCL3Wfa/Dvi8oxoGDRcXLQ7lw/N2FCe8ETNAIaFVMqPKutGDWgGptFIAC+BFrl4N9UKcknkHkpI55GAmQSc16F44N3ayqX3GIh9lei775GGI2U4+F59BFFv8j1xl7kNtS6aZavi2FtLuTSvxhqJlpLsXx9+LTnxB/0aFv+5MpGXptVzRQZs7N+cjJT6DwLs+rg4NBesamtxYf9OXXobgC3+awB0HS88Ie/noTz952muaqUle6HmT+STissuw2VWOnpGRp8Nda6LizHxD1eKi7LtG/ph64UzkC/1XQJ6BtDmSBoXgmE8XlX4iMs9lAPtI+0PzNmbxGYU73xYxrSF6RFFR6QG92jD0pHQSAitHr+drt97mGa9sgfAjBLv3Twl7zosqiwNyHNpQ8Kl/TiWFJ6xHxOB/SDsp4r+UMVLZZBWhK75T0Gi/rwsi3skBe0+2X+MVwv7ILrjKrBcUYGEkAuso328jVZPHI8nrHijjb+NX7HPdAMfCDgK8x+JfGcJFpjOAQ=
  on:
    tags: true
    repo: softbrix/dibba-tree
