language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: bg237y1HCTTa54oV5XEnPtl36EVchlRLtCTNL14Gbj1JiBm7XJ8Pn6+k+OOO7akkWvrldayqXeb9Yxq0h7JElA9mgs6X4/gVULzXuKQPVG9Qcs0ZzvOjdXkUWpvbP1MGKMOiYD5kctKpe59w+QrTWdhRA7aBdEKwfRIH5UnLBEubDzfzOKEk1JM5e9SiIHAVG99PtxjSWcOSRQCdSHDqfL7sJ5bhkFEXtAxrtNVP0KA50nU2mAWiSMeOc+LYIZPGRF3CCmvSWoBraqqpLN8PdglZRfvb177vkmIHOSSk2w47Q+Qn6E1rvGbOIhqmt/j6sKS6mfPL4qk79RlUtdnn8LsZezfoqmLGLobSPd6/xg6uRp8C9deMYd7mYXTFeEj9dN2YZ+wsbcOhMV8hSbIMgSw59MkFX0dYKY3b1q7OVqqa7t8R7M54faIfAzNmLRfCucXXpFnD5FzrsppCAcPM2/tH4IYHcL/nGBUzqr+4I8epX9HfDgpLGhE7uIKEAWZgnFeaIx0IL4MjkVjEPPZmVDwAx3WVJ0/fdBzv86hVGtQW0vTr62pws1Q55Z87iRL8P13o5ZgGUmaDj6kTTKl44MyZd28hmaowHAQ/l2g39B0FYj9wmGxztwHf9iDw1LGersZurGRJguZiXOk8BqdZznLz3sFGUZLSvet7mX3L9zk=
  on:
    tags: true
    repo: softbrix/dibba-tree
